package pn532

// ref: https://github.com/adafruit/Adafruit_Python_PN532

const (
	defaultTimeoutMs = 1000
	PREAMBLE         = 0x00
	STARTCODE1       = 0x00
	STARTCODE2       = 0xFF
	POSTAMBLE        = 0x00

	HOSTTOPN532 = 0xD4
	PN532TOHOST = 0xD5

	// PN532 Commands
	COMMAND_DIAGNOSE              = 0x00
	COMMAND_GETFIRMWAREVERSION    = 0x02
	COMMAND_GETGENERALSTATUS      = 0x04
	COMMAND_READREGISTER          = 0x06
	COMMAND_WRITEREGISTER         = 0x08
	COMMAND_READGPIO              = 0x0C
	COMMAND_WRITEGPIO             = 0x0E
	COMMAND_SETSERIALBAUDRATE     = 0x10
	COMMAND_SETPARAMETERS         = 0x12
	COMMAND_SAMCONFIGURATION      = 0x14
	COMMAND_POWERDOWN             = 0x16
	COMMAND_RFCONFIGURATION       = 0x32
	COMMAND_RFREGULATIONTEST      = 0x58
	COMMAND_INJUMPFORDEP          = 0x56
	COMMAND_INJUMPFORPSL          = 0x46
	COMMAND_INLISTPASSIVETARGET   = 0x4A
	COMMAND_INATR                 = 0x50
	COMMAND_INPSL                 = 0x4E
	COMMAND_INDATAEXCHANGE        = 0x40
	COMMAND_INCOMMUNICATETHRU     = 0x42
	COMMAND_INDESELECT            = 0x44
	COMMAND_INRELEASE             = 0x52
	COMMAND_INSELECT              = 0x54
	COMMAND_INAUTOPOLL            = 0x60
	COMMAND_TGINITASTARGET        = 0x8C
	COMMAND_TGSETGENERALBYTES     = 0x92
	COMMAND_TGGETDATA             = 0x86
	COMMAND_TGSETDATA             = 0x8E
	COMMAND_TGSETMETADATA         = 0x94
	COMMAND_TGGETINITIATORCOMMAND = 0x88
	COMMAND_TGRESPONSETOINITIATOR = 0x90
	COMMAND_TGGETTARGETSTATUS     = 0x8A

	RESPONSE_INDATAEXCHANGE      = 0x41
	RESPONSE_INLISTPASSIVETARGET = 0x4B

	WAKEUP = 0x55

	SPI_STATREAD  = 0x02
	SPI_DATAWRITE = 0x01
	SPI_DATAREAD  = 0x03
	SPI_READY     = 0x01

	I2C_ADDRESS      = 0x48 >> 1
	I2C_READBIT      = 0x01
	I2C_BUSY         = 0x00
	I2C_READY        = 0x01
	I2C_READYTIMEOUT = 20

	MIFARE_ISO14443A = 0x00

	// Mifare Commands
	MIFARE_CMD_AUTH_A           = 0x60
	MIFARE_CMD_AUTH_B           = 0x61
	MIFARE_CMD_READ             = 0x30
	MIFARE_CMD_WRITE            = 0xA0
	MIFARE_CMD_TRANSFER         = 0xB0
	MIFARE_CMD_DECREMENT        = 0xC0
	MIFARE_CMD_INCREMENT        = 0xC1
	MIFARE_CMD_STORE            = 0xC2
	MIFARE_ULTRALIGHT_CMD_WRITE = 0xA2

	// Prefixes for NDEF Records (to identify record type)
	NDEF_URIPREFIX_NONE         = 0x00
	NDEF_URIPREFIX_HTTP_WWWDOT  = 0x01
	NDEF_URIPREFIX_HTTPS_WWWDOT = 0x02
	NDEF_URIPREFIX_HTTP         = 0x03
	NDEF_URIPREFIX_HTTPS        = 0x04
	NDEF_URIPREFIX_TEL          = 0x05
	NDEF_URIPREFIX_MAILTO       = 0x06
	NDEF_URIPREFIX_FTP_ANONAT   = 0x07
	NDEF_URIPREFIX_FTP_FTPDOT   = 0x08
	NDEF_URIPREFIX_FTPS         = 0x09
	NDEF_URIPREFIX_SFTP         = 0x0A
	NDEF_URIPREFIX_SMB          = 0x0B
	NDEF_URIPREFIX_NFS          = 0x0C
	NDEF_URIPREFIX_FTP          = 0x0D
	NDEF_URIPREFIX_DAV          = 0x0E
	NDEF_URIPREFIX_NEWS         = 0x0F
	NDEF_URIPREFIX_TELNET       = 0x10
	NDEF_URIPREFIX_IMAP         = 0x11
	NDEF_URIPREFIX_RTSP         = 0x12
	NDEF_URIPREFIX_URN          = 0x13
	NDEF_URIPREFIX_POP          = 0x14
	NDEF_URIPREFIX_SIP          = 0x15
	NDEF_URIPREFIX_SIPS         = 0x16
	NDEF_URIPREFIX_TFTP         = 0x17
	NDEF_URIPREFIX_BTSPP        = 0x18
	NDEF_URIPREFIX_BTL2CAP      = 0x19
	NDEF_URIPREFIX_BTGOEP       = 0x1A
	NDEF_URIPREFIX_TCPOBEX      = 0x1B
	NDEF_URIPREFIX_IRDAOBEX     = 0x1C
	NDEF_URIPREFIX_FILE         = 0x1D
	NDEF_URIPREFIX_URN_EPC_ID   = 0x1E
	NDEF_URIPREFIX_URN_EPC_TAG  = 0x1F
	NDEF_URIPREFIX_URN_EPC_PAT  = 0x20
	NDEF_URIPREFIX_URN_EPC_RAW  = 0x21
	NDEF_URIPREFIX_URN_EPC      = 0x22
	NDEF_URIPREFIX_URN_NFC      = 0x23

	GPIO_VALIDATIONBIT = 0x80
)

const (
	_ = iota
	modeI2C
	modeSPI
	modeHWSPI
)

var (
	ackBytes             = []byte{0x01, 0x00, 0x00, 0xFF, 0x00, 0xFF, 0x00}
	frameStartBytes      = []byte{0x01, 0x00, 0x00, 0xFF}
	responseFirmwarevers = []byte{0x00, 0xFF, 0x06, 0xFA, 0xD5, 0x03}
)
